@echo off
echo ============================================
echo   Python to EXE Builder
echo   Generated by code-format.com
echo ============================================
echo.

REM Check Python
python --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not in PATH.
    echo Download Python from https://www.python.org/downloads/
    pause
    exit /b 1
)
echo [OK] Python found.

REM Install PyInstaller
echo [INFO] Installing PyInstaller...
pip install pyinstaller
if errorlevel 1 (
    echo [ERROR] Failed to install PyInstaller.
    pause
    exit /b 1
)
echo [OK] PyInstaller installed.

REM Run PyInstaller
echo [INFO] Building executable...
pyinstaller --onefile my_script.py
if errorlevel 1 (
    echo [ERROR] Build failed. Check the output above for details.
    pause
    exit /b 1
)

echo.
echo ============================================
echo   Build complete!
echo   Your executable is in the dist\ folder.
echo ============================================
echo.
if exist "dist\my_script.exe" (
    echo   File: dist\my_script.exe
) else (
    echo   Check the dist\ folder for your executable.
)
echo.
pause